version: '3'
services:
  arangodb:
    container_name: arango-<%= name %>
    image: arangodb/arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - 8529:8529
    command:
      - arangod
      - --http.hide-product-header=true
      #- --server.storage-engine=rocksdb
